// ═══════════════════════════════════════════════════════
// AUDIT PAGE — SHARED STATIC DATA
// Import from this file in every tab: import { ... } from './auditData';
// ═══════════════════════════════════════════════════════

import {
  AuditLog,
  SecurityEvent,
  DataChange,
  AccessLog,
  ExportLog,
  ActiveSession,
} from "./types";

// ── LOOKUP MAPS ───────────────────────────────────────────
export const STAFF_COLORS: Record<string, string> = {
  "Admin Khan": "#FF6A00",
  "Sara Khan": "#8B5CF6",
  "Bilal Raza": "#2563EB",
  "Amna Siddiqui": "#EC4899",
  "Tariq Mehmood": "#0891B2",
  "Fatima Noor": "#059669",
  "Hassan Ali": "#7C3AED",
  "Omar Farooq": "#16A34A",
  System: "#6B7280",
  "Imran Qureshi": "#DC2626",
  "Nadia Malik": "#D97706",
  "Usman Ghani": "#0369A1",
  Unknown: "#DC2626",
  "Zara Hussain": "#DB2777",
};

export const MODULE_ICONS: Record<string, string> = {
  Orders: "fa-bag-shopping",
  Products: "fa-box-open",
  Inventory: "fa-warehouse",
  Finance: "fa-coins",
  Customers: "fa-users",
  Couriers: "fa-truck",
  Riders: "fa-person-biking",
  Staff: "fa-id-badge",
  Reports: "fa-chart-pie",
  Settings: "fa-gear",
  System: "fa-server",
  Security: "fa-shield-halved",
};

// ── CHIP DEFINITIONS ──────────────────────────────────────
export const CHIPS = [
  { label: "All Events", filter: "", icon: "fa-list" },
  {
    label: "Critical",
    filter: "Critical",
    icon: "fa-circle-exclamation",
    iconColor: "var(--red)",
  },
  {
    label: "Warning",
    filter: "Warning",
    icon: "fa-triangle-exclamation",
    iconColor: "var(--yellow)",
  },
  {
    label: "Info",
    filter: "Info",
    icon: "fa-circle-info",
    iconColor: "var(--blue)",
  },
  { label: "Orders", filter: "Orders" },
  { label: "Inventory", filter: "Inventory" },
  { label: "Finance", filter: "Finance" },
  { label: "Settings", filter: "Settings" },
  { label: "System", filter: "System" },
];

// ── ALL LOGS ──────────────────────────────────────────────
export const ALL_LOGS_DATA: AuditLog[] = [
  {
    id: "EVT-00348",
    ts: "11 May 2026 16:30",
    staff: "Admin Khan",
    action: "Database backup triggered manually",
    module: "System",
    detail: "Backup size: 4.2MB. Destination: Local Server.",
    ip: "192.168.1.5",
    device: "Chrome 124 / Windows 11",
    severity: "Info",
  },
  {
    id: "EVT-00347",
    ts: "11 May 2026 16:00",
    staff: "Zara Hussain",
    action: "Edited customer delivery address",
    module: "Customers",
    detail: "Customer: Sara Bano · ORD-1051 address updated.",
    ip: "192.168.1.22",
    device: "Chrome 124 / Android",
    severity: "Info",
  },
  {
    id: "EVT-00346",
    ts: "11 May 2026 15:45",
    staff: "Fatima Noor",
    action: "Supplier payment recorded",
    module: "Finance",
    detail: "Supplier: Gul Ahmed · Amount: ₨45,000 via Bank Transfer.",
    ip: "192.168.1.12",
    device: "Firefox 126 / Windows 10",
    severity: "Info",
  },
  {
    id: "EVT-00345",
    ts: "11 May 2026 15:20",
    staff: "Imran Qureshi",
    action: "Updated delivery status to In Transit",
    module: "Riders",
    detail: "Order ORD-1050 · Tracking updated from Pending to In Transit.",
    ip: "10.0.0.22",
    device: "Chrome 124 / Android",
    severity: "Info",
  },
  {
    id: "EVT-00344",
    ts: "11 May 2026 15:00",
    staff: "Admin Khan",
    action: "Email notification settings updated",
    module: "Settings",
    detail: "Setting changed: Email notifications for Orders → Enabled.",
    ip: "192.168.1.5",
    device: "Chrome 124 / Windows 11",
    severity: "Warning",
  },
  {
    id: "EVT-00343",
    ts: "11 May 2026 14:30",
    staff: "Bilal Raza",
    action: "Low stock threshold overridden",
    module: "Inventory",
    detail:
      "SKU-0028 threshold changed from 10 → 5. Reason: Seasonal adjustment.",
    ip: "10.0.0.14",
    device: "Safari 17 / iPhone 15",
    severity: "Warning",
  },
  {
    id: "EVT-00342",
    ts: "11 May 2026 14:00",
    staff: "Sara Khan",
    action: "Created 5 new orders (batch entry)",
    module: "Orders",
    detail: "Orders ORD-1053 to ORD-1057 created in batch from WhatsApp.",
    ip: "192.168.1.8",
    device: "Chrome 124 / Windows 10",
    severity: "Info",
  },
  {
    id: "EVT-00341",
    ts: "11 May 2026 13:20",
    staff: "Usman Ghani",
    action: "Expense entry logged",
    module: "Finance",
    detail: "Category: Operations · Amount: ₨2,200 · Ref: Packaging supplies.",
    ip: "192.168.1.18",
    device: "Firefox 126 / Windows 10",
    severity: "Info",
  },
  {
    id: "EVT-00340",
    ts: "11 May 2026 13:00",
    staff: "Admin Khan",
    action: "Product pricing modified",
    module: "Products",
    detail: "SKU-0183 (Chiffon Saree Pink) · Price changed: ₨7,200 → ₨7,500.",
    ip: "192.168.1.5",
    device: "Chrome 124 / Windows 11",
    severity: "Warning",
  },
  {
    id: "EVT-00339",
    ts: "11 May 2026 12:30",
    staff: "Nadia Malik",
    action: "Order ORD-1046 cancelled",
    module: "Orders",
    detail: "Reason: Customer request. COD refund initiated.",
    ip: "192.168.1.20",
    device: "Chrome 124 / Windows 10",
    severity: "Warning",
  },
  {
    id: "EVT-00338",
    ts: "11 May 2026 12:15",
    staff: "Tariq Mehmood",
    action: "Failed login attempt",
    module: "Security",
    detail:
      "5th consecutive failed login from IP 203.55.41.12. IP auto-blocked.",
    ip: "203.55.41.12",
    device: "Unknown",
    severity: "Critical",
  },
  {
    id: "EVT-00337",
    ts: "11 May 2026 12:00",
    staff: "Omar Farooq",
    action: "Delivery confirmed as Delivered",
    module: "Riders",
    detail: "Order ORD-1044 · Customer: Rabia Ahmed · COD collected: ₨2,200.",
    ip: "10.0.0.35",
    device: "Samsung Internet / Android",
    severity: "Info",
  },
  {
    id: "EVT-00336",
    ts: "11 May 2026 11:30",
    staff: "Admin Khan",
    action: "Role changed for Rabia Tanvir",
    module: "Staff",
    detail: "Role: Sales Operator → Status: Suspended. Reason logged by Admin.",
    ip: "192.168.1.5",
    device: "Chrome 124 / Windows 11",
    severity: "Warning",
  },
  {
    id: "EVT-00335",
    ts: "11 May 2026 11:00",
    staff: "Sara Khan",
    action: "Sales report exported",
    module: "Reports",
    detail: "May 2026 Sales Data · Format: CSV · 312 records.",
    ip: "192.168.1.8",
    device: "Chrome 124 / Windows 10",
    severity: "Info",
  },
  {
    id: "EVT-00334",
    ts: "11 May 2026 10:44",
    staff: "Fatima Noor",
    action: "COD collection recorded",
    module: "Finance",
    detail: "Order ORD-1052 · Rider: Usman Ahmed · Amount: ₨5,400.",
    ip: "192.168.1.12",
    device: "Firefox 126 / Windows 10",
    severity: "Info",
  },
  {
    id: "EVT-00333",
    ts: "11 May 2026 10:20",
    staff: "Amna Siddiqui",
    action: "New customer profile created",
    module: "Customers",
    detail: "Customer: Aisha Bhatti · Phone: 0300-1122334 · Lahore.",
    ip: "192.168.1.22",
    device: "Chrome 124 / Android",
    severity: "Info",
  },
  {
    id: "EVT-00332",
    ts: "11 May 2026 10:03",
    staff: "Bilal Raza",
    action: "Stock added for SKU-0041",
    module: "Inventory",
    detail:
      "SKU-0041 (Classic Lawn Suit) · Qty: +30 · Reason: Supplier restock.",
    ip: "10.0.0.14",
    device: "Safari 17 / iPhone 15",
    severity: "Info",
  },
  {
    id: "EVT-00331",
    ts: "11 May 2026 10:00",
    staff: "Unknown",
    action: "Failed login attempt (x3)",
    module: "Security",
    detail: "3 failed attempts in 10 minutes from IP 203.55.41.12.",
    ip: "203.55.41.12",
    device: "Unknown",
    severity: "Critical",
  },
  {
    id: "EVT-00330",
    ts: "11 May 2026 09:45",
    staff: "Sara Khan",
    action: "Order ORD-1052 status updated to Packed",
    module: "Orders",
    detail: "Order status changed: Confirmed → Packed by Sara Khan.",
    ip: "192.168.1.8",
    device: "Chrome 124 / Windows 10",
    severity: "Info",
  },
  {
    id: "EVT-00329",
    ts: "11 May 2026 09:30",
    staff: "Sara Khan",
    action: "Password changed",
    module: "Security",
    detail: "Password updated by user via profile settings.",
    ip: "192.168.1.8",
    device: "Chrome 124 / Windows 10",
    severity: "Warning",
  },
  {
    id: "EVT-00328",
    ts: "11 May 2026 09:15",
    staff: "Bilal Raza",
    action: "Logged in successfully",
    module: "System",
    detail: "Login from new device: Safari 17 / iPhone 15.",
    ip: "10.0.0.14",
    device: "Safari 17 / iPhone 15",
    severity: "Warning",
  },
  {
    id: "EVT-00327",
    ts: "11 May 2026 09:10",
    staff: "Sara Khan",
    action: "Logged in successfully",
    module: "System",
    detail: "Regular login from known device.",
    ip: "192.168.1.8",
    device: "Chrome 124 / Windows 10",
    severity: "Info",
  },
  {
    id: "EVT-00326",
    ts: "11 May 2026 09:02",
    staff: "Admin Khan",
    action: "Logged in successfully",
    module: "System",
    detail: "Regular login from known device.",
    ip: "192.168.1.5",
    device: "Chrome 124 / Windows 11",
    severity: "Info",
  },
  {
    id: "EVT-00325",
    ts: "11 May 2026 09:00",
    staff: "System",
    action: "Scheduled backup completed",
    module: "System",
    detail: "Daily backup successful. Size: 4.2MB. Duration: 12s.",
    ip: "127.0.0.1",
    device: "System Process",
    severity: "Info",
  },
  {
    id: "EVT-00324",
    ts: "10 May 2026 18:00",
    staff: "Bilal Raza",
    action: "Logged in successfully",
    module: "System",
    detail: "Regular login from known IP.",
    ip: "192.168.1.8",
    device: "Safari 17 / iPhone 15",
    severity: "Info",
  },
  {
    id: "EVT-00323",
    ts: "10 May 2026 17:30",
    staff: "System",
    action: "IP address blocked",
    module: "Security",
    detail: "IP 203.55.41.12 blocked after 5 failed login attempts.",
    ip: "127.0.0.1",
    device: "System Process",
    severity: "Critical",
  },
  {
    id: "EVT-00322",
    ts: "10 May 2026 17:00",
    staff: "Fatima Noor",
    action: "Financial report exported",
    module: "Reports",
    detail: "April 2026 Financial Records · Format: Excel · 892 records.",
    ip: "192.168.1.12",
    device: "Firefox 126 / Windows 10",
    severity: "Info",
  },
  {
    id: "EVT-00321",
    ts: "10 May 2026 16:30",
    staff: "Amna Siddiqui",
    action: "Bulk order import completed",
    module: "Orders",
    detail: "12 orders imported from Shopify sync. 0 errors.",
    ip: "192.168.1.22",
    device: "Chrome 124 / Android",
    severity: "Info",
  },
  {
    id: "EVT-00320",
    ts: "10 May 2026 15:00",
    staff: "Admin Khan",
    action: "Courier API key updated for Trax",
    module: "Settings",
    detail:
      "Trax courier API credentials updated. New key tested successfully.",
    ip: "192.168.1.5",
    device: "Chrome 124 / Windows 11",
    severity: "Warning",
  },
  {
    id: "EVT-00319",
    ts: "10 May 2026 14:20",
    staff: "Sara Khan",
    action: "Stock adjustment — damage write-off",
    module: "Inventory",
    detail: "SKU-0055 (Printed Lawn 3PC) · -1 unit · Reason: Damage.",
    ip: "192.168.1.8",
    device: "Chrome 124 / Windows 10",
    severity: "Warning",
  },
];

// ── SECURITY ──────────────────────────────────────────────
export const SECURITY_DATA: SecurityEvent[] = [
  {
    ts: "11 May 2026 12:15",
    event: "IP Auto-Blocked",
    user: "System",
    ip: "203.55.41.12",
    device: "System Process",
    location: "Unknown",
    severity: "Critical",
    outcome: "Blocked",
  },
  {
    ts: "11 May 2026 12:00",
    event: "5x Failed Login",
    user: "Unknown",
    ip: "203.55.41.12",
    device: "Unknown Browser",
    location: "Unknown",
    severity: "Critical",
    outcome: "Blocked",
  },
  {
    ts: "11 May 2026 10:00",
    event: "3x Failed Login",
    user: "Unknown",
    ip: "203.55.41.12",
    device: "Unknown Browser",
    location: "Unknown",
    severity: "Critical",
    outcome: "Flagged",
  },
  {
    ts: "11 May 2026 11:30",
    event: "Role Changed",
    user: "Admin Khan",
    ip: "192.168.1.5",
    device: "Chrome / Windows",
    location: "Lahore, PK",
    severity: "Warning",
    outcome: "Completed",
  },
  {
    ts: "11 May 2026 09:30",
    event: "Password Changed",
    user: "Sara Khan",
    ip: "192.168.1.8",
    device: "Chrome / Windows",
    location: "Lahore, PK",
    severity: "Warning",
    outcome: "Completed",
  },
  {
    ts: "11 May 2026 09:15",
    event: "Login — New Device",
    user: "Bilal Raza",
    ip: "10.0.0.14",
    device: "Safari / iPhone 15",
    location: "Lahore, PK",
    severity: "Warning",
    outcome: "Allowed",
  },
  {
    ts: "10 May 2026 17:30",
    event: "IP Auto-Blocked",
    user: "System",
    ip: "185.220.101.33",
    device: "System Process",
    location: "Unknown (VPN)",
    severity: "Critical",
    outcome: "Blocked",
  },
  {
    ts: "10 May 2026 15:00",
    event: "API Key Updated",
    user: "Admin Khan",
    ip: "192.168.1.5",
    device: "Chrome / Windows",
    location: "Lahore, PK",
    severity: "Warning",
    outcome: "Completed",
  },
  {
    ts: "09 May 2026 16:30",
    event: "Failed Login",
    user: "Unknown",
    ip: "185.220.101.33",
    device: "Tor Browser",
    location: "Unknown (VPN)",
    severity: "Critical",
    outcome: "Blocked",
  },
  {
    ts: "09 May 2026 11:00",
    event: "2FA Setup Skipped",
    user: "Tariq Mehmood",
    ip: "10.0.0.22",
    device: "Chrome / Android",
    location: "Lahore, PK",
    severity: "Warning",
    outcome: "Noted",
  },
];

// ── DATA CHANGES ──────────────────────────────────────────
export const DATA_CHANGES: DataChange[] = [
  {
    ts: "11 May 2026 16:00",
    staff: "Zara Hussain",
    module: "Customers",
    type: "Update",
    record: "Cust-03214",
    field: "Delivery Address",
    oldVal: "House 12, Gulberg III",
    newVal: "House 14, Gulberg III",
  },
  {
    ts: "11 May 2026 15:00",
    staff: "Admin Khan",
    module: "Settings",
    type: "Update",
    record: "System Config",
    field: "Email Notifications",
    oldVal: "Disabled",
    newVal: "Enabled",
  },
  {
    ts: "11 May 2026 14:30",
    staff: "Bilal Raza",
    module: "Inventory",
    type: "Update",
    record: "SKU-0028",
    field: "Low Stock Threshold",
    oldVal: "10",
    newVal: "5",
  },
  {
    ts: "11 May 2026 14:00",
    staff: "Sara Khan",
    module: "Orders",
    type: "Create",
    record: "ORD-1053 to ORD-1057",
    field: "—",
    oldVal: "—",
    newVal: "5 orders created",
  },
  {
    ts: "11 May 2026 13:00",
    staff: "Admin Khan",
    module: "Products",
    type: "Update",
    record: "SKU-0183",
    field: "Sale Price",
    oldVal: "₨7,200",
    newVal: "₨7,500",
  },
  {
    ts: "11 May 2026 12:30",
    staff: "Nadia Malik",
    module: "Orders",
    type: "Update",
    record: "ORD-1046",
    field: "Status",
    oldVal: "Shipped",
    newVal: "Cancelled",
  },
  {
    ts: "11 May 2026 10:03",
    staff: "Bilal Raza",
    module: "Inventory",
    type: "Stock Adjustment",
    record: "SKU-0041",
    field: "Quantity",
    oldVal: "3",
    newVal: "33",
  },
  {
    ts: "11 May 2026 09:45",
    staff: "Sara Khan",
    module: "Orders",
    type: "Update",
    record: "ORD-1052",
    field: "Status",
    oldVal: "Confirmed",
    newVal: "Packed",
  },
  {
    ts: "10 May 2026 19:20",
    staff: "Admin Khan",
    module: "Staff",
    type: "Update",
    record: "Rabia Tanvir",
    field: "Account Status",
    oldVal: "Active",
    newVal: "Suspended",
  },
  {
    ts: "10 May 2026 17:00",
    staff: "Sara Khan",
    module: "Inventory",
    type: "Stock Adjustment",
    record: "SKU-0055",
    field: "Quantity",
    oldVal: "29",
    newVal: "28",
  },
  {
    ts: "10 May 2026 16:30",
    staff: "Amna Siddiqui",
    module: "Orders",
    type: "Bulk Import",
    record: "12 orders",
    field: "—",
    oldVal: "—",
    newVal: "12 orders from Shopify sync",
  },
  {
    ts: "10 May 2026 15:00",
    staff: "Admin Khan",
    module: "Settings",
    type: "Update",
    record: "Trax API Key",
    field: "API Credentials",
    oldVal: "TRAX-••••OLD",
    newVal: "TRAX-••••NEW",
  },
  {
    ts: "10 May 2026 11:00",
    staff: "Bilal Raza",
    module: "Products",
    type: "Create",
    record: "SKU-0251",
    field: "—",
    oldVal: "—",
    newVal: "New product: Chikan Kari Kurti",
  },
  {
    ts: "09 May 2026 14:30",
    staff: "Admin Khan",
    module: "Customers",
    type: "Delete",
    record: "Cust-02891",
    field: "—",
    oldVal: "Duplicate Record",
    newVal: "[Deleted]",
  },
  {
    ts: "09 May 2026 10:00",
    staff: "Sara Khan",
    module: "Orders",
    type: "Bulk Import",
    record: "48 orders",
    field: "—",
    oldVal: "—",
    newVal: "48 orders from CSV import",
  },
];

// ── ACCESS LOGS ───────────────────────────────────────────
export const ACCESS_DATA: AccessLog[] = [
  {
    ts: "11 May 2026 16:45",
    user: "Admin Khan",
    role: "Administrator",
    event: "Logged Out",
    ip: "192.168.1.5",
    device: "Chrome 124 / Windows 11",
    location: "Lahore, PK",
    result: "Success",
  },
  {
    ts: "11 May 2026 09:02",
    user: "Admin Khan",
    role: "Administrator",
    event: "Logged In",
    ip: "192.168.1.5",
    device: "Chrome 124 / Windows 11",
    location: "Lahore, PK",
    result: "Success",
  },
  {
    ts: "11 May 2026 09:10",
    user: "Sara Khan",
    role: "Ops Manager",
    event: "Logged In",
    ip: "192.168.1.8",
    device: "Chrome 124 / Windows 10",
    location: "Lahore, PK",
    result: "Success",
  },
  {
    ts: "11 May 2026 09:15",
    user: "Bilal Raza",
    role: "Inventory Manager",
    event: "Logged In (New Device)",
    ip: "10.0.0.14",
    device: "Safari 17 / iPhone 15",
    location: "Lahore, PK",
    result: "Warning",
  },
  {
    ts: "11 May 2026 09:30",
    user: "Amna Siddiqui",
    role: "Sales Operator",
    event: "Logged In",
    ip: "192.168.1.22",
    device: "Chrome 124 / Android",
    location: "Lahore, PK",
    result: "Success",
  },
  {
    ts: "11 May 2026 09:45",
    user: "Fatima Noor",
    role: "Accounts",
    event: "Logged In",
    ip: "192.168.1.12",
    device: "Firefox 126 / Windows 10",
    location: "Lahore, PK",
    result: "Success",
  },
  {
    ts: "11 May 2026 10:00",
    user: "Unknown",
    role: "—",
    event: "Failed Login (x3)",
    ip: "203.55.41.12",
    device: "Unknown",
    location: "Unknown",
    result: "Blocked",
  },
  {
    ts: "11 May 2026 10:10",
    user: "Hassan Ali",
    role: "Courier Handler",
    event: "Logged In",
    ip: "192.168.1.18",
    device: "Chrome 124 / Windows 11",
    location: "Lahore, PK",
    result: "Success",
  },
  {
    ts: "11 May 2026 10:30",
    user: "Omar Farooq",
    role: "Rider",
    event: "Logged In",
    ip: "10.0.0.35",
    device: "Samsung Internet / Android",
    location: "Lahore, PK",
    result: "Success",
  },
  {
    ts: "11 May 2026 11:00",
    user: "Imran Qureshi",
    role: "Rider",
    event: "Logged In",
    ip: "10.0.0.22",
    device: "Chrome 124 / Android",
    location: "Lahore, PK",
    result: "Success",
  },
  {
    ts: "11 May 2026 12:00",
    user: "Unknown",
    role: "—",
    event: "Failed Login (x5)",
    ip: "203.55.41.12",
    device: "Unknown",
    location: "Unknown",
    result: "Blocked",
  },
  {
    ts: "10 May 2026 09:00",
    user: "Admin Khan",
    role: "Administrator",
    event: "Logged In",
    ip: "192.168.1.5",
    device: "Chrome 124 / Windows 11",
    location: "Lahore, PK",
    result: "Success",
  },
  {
    ts: "10 May 2026 08:45",
    user: "Sara Khan",
    role: "Ops Manager",
    event: "Logged In",
    ip: "192.168.1.8",
    device: "Chrome 124 / Windows 10",
    location: "Lahore, PK",
    result: "Success",
  },
  {
    ts: "09 May 2026 16:30",
    user: "Unknown",
    role: "—",
    event: "Failed Login",
    ip: "185.220.101.33",
    device: "Tor Browser",
    location: "Unknown (VPN)",
    result: "Blocked",
  },
];

// ── EXPORTS ───────────────────────────────────────────────
export const EXPORTS_DATA: ExportLog[] = [
  {
    ts: "11 May 2026 14:00",
    by: "Admin Khan",
    type: "Orders (All)",
    range: "May 2026",
    records: "1,284",
    format: "CSV",
    size: "48 KB",
    sensitive: false,
    status: "Completed",
  },
  {
    ts: "11 May 2026 11:00",
    by: "Sara Khan",
    type: "Sales Data",
    range: "May 2026",
    records: "312",
    format: "CSV",
    size: "22 KB",
    sensitive: false,
    status: "Completed",
  },
  {
    ts: "11 May 2026 09:30",
    by: "Fatima Noor",
    type: "Financial Records",
    range: "Apr 2026",
    records: "892",
    format: "Excel",
    size: "61 KB",
    sensitive: true,
    status: "Completed",
  },
  {
    ts: "10 May 2026 17:00",
    by: "Admin Khan",
    type: "Full System Export",
    range: "All Data",
    records: "—",
    format: "JSON",
    size: "2.1 MB",
    sensitive: true,
    status: "Completed",
  },
  {
    ts: "10 May 2026 16:30",
    by: "Amna Siddiqui",
    type: "Customer Data",
    range: "All Time",
    records: "3,142",
    format: "CSV",
    size: "180 KB",
    sensitive: true,
    status: "Completed",
  },
  {
    ts: "09 May 2026 14:00",
    by: "Admin Khan",
    type: "Audit Logs",
    range: "Last 30 Days",
    records: "4,820",
    format: "CSV",
    size: "310 KB",
    sensitive: true,
    status: "Completed",
  },
  {
    ts: "08 May 2026 11:30",
    by: "Sara Khan",
    type: "Inventory Data",
    range: "Snapshot",
    records: "248",
    format: "Excel",
    size: "34 KB",
    sensitive: false,
    status: "Completed",
  },
  {
    ts: "07 May 2026 16:00",
    by: "Admin Khan",
    type: "Staff Report",
    range: "Apr 2026",
    records: "14",
    format: "Excel",
    size: "18 KB",
    sensitive: true,
    status: "Completed",
  },
  {
    ts: "01 May 2026 08:30",
    by: "Admin Khan",
    type: "Sales Data",
    range: "Apr 2026",
    records: "421",
    format: "CSV",
    size: "44 KB",
    sensitive: false,
    status: "Completed",
  },
  {
    ts: "01 May 2026 08:20",
    by: "Fatima Noor",
    type: "COD Reconciliation Report",
    range: "Apr 2026",
    records: "186",
    format: "PDF",
    size: "24 KB",
    sensitive: false,
    status: "Completed",
  },
];

// ── ACTIVE SESSIONS ───────────────────────────────────────
export const ACTIVE_SESSIONS: ActiveSession[] = [
  {
    user: "Admin Khan",
    role: "Administrator",
    color: "#FF6A00",
    ip: "192.168.1.5",
    device: "Chrome / Windows 11",
    since: "09:02",
  },
  {
    user: "Sara Khan",
    role: "Ops Manager",
    color: "#8B5CF6",
    ip: "192.168.1.8",
    device: "Chrome / Windows 10",
    since: "09:10",
  },
  {
    user: "Fatima Noor",
    role: "Accounts",
    color: "#059669",
    ip: "192.168.1.12",
    device: "Firefox / Windows 10",
    since: "09:45",
  },
  {
    user: "Omar Farooq",
    role: "Rider",
    color: "#16A34A",
    ip: "10.0.0.35",
    device: "Samsung / Android",
    since: "10:30",
  },
];

// ── ANALYTICS DATA ────────────────────────────────────────
export const MODULE_BREAKDOWN = [
  { name: "Orders", count: 88, color: "var(--accent)" },
  { name: "Inventory", count: 54, color: "var(--green)" },
  { name: "System", count: 48, color: "#6B7280" },
  { name: "Finance", count: 40, color: "var(--teal)" },
  { name: "Products", count: 35, color: "var(--blue)" },
  { name: "Security", count: 22, color: "var(--red)" },
  { name: "Settings", count: 18, color: "var(--yellow)" },
  { name: "Customers", count: 16, color: "var(--purple)" },
  { name: "Reports", count: 14, color: "#0891B2" },
  { name: "Staff", count: 13, color: "#DB2777" },
];

export const STAFF_ACTIVITY_ANALYTICS = [
  { name: "Admin Khan", count: 72, color: "#FF6A00" },
  { name: "Sara Khan", count: 58, color: "#8B5CF6" },
  { name: "Amna Siddiqui", count: 44, color: "#EC4899" },
  { name: "Bilal Raza", count: 38, color: "#2563EB" },
  { name: "Tariq Mehmood", count: 32, color: "#0891B2" },
  { name: "Fatima Noor", count: 28, color: "#059669" },
  { name: "Hassan Ali", count: 22, color: "#7C3AED" },
  { name: "Omar Farooq", count: 18, color: "#16A34A" },
];

export const HOURLY_COUNTS = [4, 12, 28, 35, 42, 38, 22, 45, 52, 48, 31, 18];
export const HOURLY_LABELS = [
  "08:00",
  "09:00",
  "10:00",
  "11:00",
  "12:00",
  "13:00",
  "14:00",
  "15:00",
  "16:00",
  "17:00",
  "18:00",
  "19:00",
];

export const TOP_ACTIONS = [
  { action: "Order Status Updated", count: 68 },
  { action: "Staff Login", count: 42 },
  { action: "Stock Level Changed", count: 38 },
  { action: "COD Collection Recorded", count: 24 },
  { action: "Customer Record Updated", count: 19 },
  { action: "Order Created", count: 17 },
  { action: "Report Exported", count: 14 },
  { action: "Settings Modified", count: 11 },
  { action: "Product Price Changed", count: 8 },
  { action: "Failed Login Attempt", count: 7 },
];

export const SEV_DATA = [
  { s: "Info", n: 298, c: "var(--blue)" },
  { s: "Warning", n: 42, c: "var(--yellow)" },
  { s: "Critical", n: 8, c: "var(--red)" },
];

export const SPARKLINE_DAYS = [
  "5 May",
  "6 May",
  "7 May",
  "8 May",
  "9 May",
  "10 May",
  "11 May",
];
export const SPARKLINE_SUCCESS = [14, 18, 12, 22, 16, 20, 9];
export const SPARKLINE_FAILED = [1, 0, 2, 0, 3, 1, 5];
