// CRUD_Project/server/models/Order.js
const f530ui = require("mongoose");
const {
  v4: z34scf
} = require("uuid");

// ============================================================================
// Order Item Sub-Schema
// ============================================================================
const it5624 = new f530ui.Schema({
  productId: {
    type: f530ui.Schema.Types.ObjectId,
    ref: "Product",
    required: true,
    index: true
  },
  variantId: {
    type: String,
    required: true,
    index: true
  },
  name: {
    type: String,
    required: true,
    trim: true
  },
  sku: {
    type: String,
    required: true,
    trim: true
  },
  variantAttributes: {
    type: Map,
    of: String,
    default: {}
  },
  quantity: {
    type: Number,
    required: true,
    min: 1
  },
  unitPrice: {
    type: Number,
    required: true,
    min: 0
  },
  totalPrice: {
    type: Number,
    required: true,
    min: 0
  }
});

// ============================================================================
// Shipping Address Sub-Schema
// ============================================================================
const t87u = new f530ui.Schema({
  name: {
    type: String,
    required: true,
    trim: true
  },
  phone: {
    type: String,
    required: true,
    trim: true
  },
  street: {
    type: String,
    required: true,
    trim: true
  },
  city: {
    type: String,
    required: true,
    trim: true
  },
  state: {
    type: String,
    trim: true
  },
  zipCode: {
    type: String,
    required: true,
    trim: true
  },
  country: {
    type: String,
    required: true,
    trim: true
  }
}, {
  _id: false
});

// ============================================================================
// Main Order Schema
// ============================================================================
const gs1u = new f530ui.Schema({
  // ✅ REQUIRED: Human-readable order ID (auto-generated by pre-save hook)
  orderId: {
    type: String,
    required: true,
    unique: true,
    index: true,
    // ✅ UUID-based unique ID
    default: () => `ORD-${z34scf().split("-")[0].toUpperCase()}`
  },
  source: {
    type: String,
    enum: ["WhatsApp", "Shopify", "Manual", "Instagram", "Website"],
    required: true,
    index: true
  },
  shopifyOrderId: {
    type: String,
    sparse: true,
    unique: true,
    index: true
  },
  customer: {
    type: f530ui.Schema.Types.ObjectId,
    ref: "Customer",
    required: true,
    index: true
  },
  shippingAddress: {
    type: t87u,
    required: true
  },
  items: [it5624],
  subtotal: {
    type: Number,
    required: true,
    min: 0
  },
  shippingCost: {
    type: Number,
    default: 0,
    min: 0
  },
  discount: {
    type: Number,
    default: 0,
    min: 0
  },
  totalAmount: {
    type: Number,
    required: true,
    min: 0
  },
  paymentStatus: {
    type: String,
    enum: ["Pending", "Paid", "Refunded", "Partially Paid", "Failed"],
    default: "Pending",
    index: true
  },
  paymentMethod: {
    type: String,
    enum: ["COD", "Prepaid", "Card", "BankTransfer", "Wallet"],
    index: true
  },
  orderStatus: {
    type: String,
    enum: ["Pending", "Confirmed", "Processing", "Packed", "Shipped", "Delivered", "Cancelled", "Returned"],
    default: "Pending",
    index: true
  },
  courier: {
    type: f530ui.Schema.Types.ObjectId,
    ref: "Courier",
    index: true
  },
  rider: {
    type: f530ui.Schema.Types.ObjectId,
    ref: "User",
    index: true
  },
  trackingNumber: {
    type: String,
    trim: true,
    sparse: true,
    index: true
  },
  deliveryStatus: {
    type: String,
    enum: ["Pending", "Assigned", "Picked Up", "In Transit", "Out for Delivery", "Delivered", "Failed", "Returned"],
    default: "Pending",
    index: true
  },
  notes: {
    type: String,
    trim: true
  },
  placedBy: {
    type: f530ui.Schema.Types.ObjectId,
    ref: "User",
    required: true,
    index: true
  },
  tenantId: {
    type: f530ui.Schema.Types.ObjectId,
    ref: "Tenant",
    required: true,
    index: true
  },
  createdAt: {
    type: Date,
    default: Date.now
  },
  updatedAt: {
    type: Date,
    default: Date.now
  },
  deliveredAt: {
    type: Date
  }
}, {
  timestamps: true,
  toJSON: {
    virtuals: true
  },
  toObject: {
    virtuals: true
  }
});

// ============================================================================
// 🔐 Pre-Save Hook: Auto-Generate orderId (FIXED for Mongoose 9.x)
// ============================================================================
// ✅ Use async function WITHOUT next parameter
gs1u.pre("save", async function () {
  // Only generate orderId for NEW documents that don't already have one
  if (this.isNew && !this.orderId) {
    const c481 = new Date().getFullYear();

    // Find the last order of this year to get the next sequence number
    const tvo84j = await this.constructor.findOne({
      orderId: new RegExp(`^ORD-${c481}-`)
    }).sort({
      orderId: -1
    }).select("orderId").lean();
    let is8di = 1;
    if (tvo84j?.orderId) {
      // Extract the number: ORD-2026-000001 → 1
      const z4wqx = parseInt(tvo84j.orderId.split("-")[2], 10);
      is8di = z4wqx + 1;
    }

    // Generate orderId: ORD-2026-000001 (6-digit sequence)
    this.orderId = `ORD-${c481}-${String(is8di).padStart(6, "0")}`;

    // Debug log (remove in production)
    if (process.env.NODE_ENV === "development") {
      console.log("🔍 [DEBUG] Generated orderId:", this.orderId);
    }
  }
  // ✅ No next() call needed - Mongoose 9.x handles async automatically
});

// ============================================================================
// 🔢 Pre-Save Hook: Validate totalAmount (FIXED for Mongoose 9.x)
// ============================================================================
gs1u.pre("save", async function () {
  const ku7q = this.subtotal + this.shippingCost - this.discount;

  // Allow small floating point differences (< 0.01)
  if (Math.abs(this.totalAmount - ku7q) > 0.01) {
    throw new Error(`Total amount mismatch: expected ${ku7q.toFixed(2)}, got ${this.totalAmount.toFixed(2)}`);
  }
  // ✅ No next() call needed
});

// ============================================================================
// Indexes for Common Queries
// ============================================================================
gs1u.index({
  customer: 1,
  createdAt: -1
});
gs1u.index({
  orderStatus: 1,
  paymentStatus: 1
});
gs1u.index({
  "items.productId": 1,
  createdAt: -1
});
gs1u.index({
  source: 1,
  createdAt: -1
});
gs1u.index({
  deliveredAt: 1
}, {
  sparse: true
});
gs1u.index({
  tenantId: 1,
  createdAt: -1
});
gs1u.index({
  tenantId: 1,
  orderId: 1
}, {
  unique: true
});
gs1u.index({
  tenantId: 1,
  shopifyOrderId: 1
}, {
  unique: true,
  sparse: true
});

// ============================================================================
// Virtuals
// ============================================================================

// Virtual: Total item count
gs1u.virtual("itemCount").get(function () {
  return this.items.reduce((bk6ofq, hy91a2) => bk6ofq + hy91a2.quantity, 0);
});

// Virtual: Is order overdue (shipped but not delivered in 7 days)
gs1u.virtual("isOverdue").get(function () {
  if (this.orderStatus !== "Shipped") return false;
  const u199r = new Date();
  u199r.setDate(u199r.getDate() - 7);
  return this.updatedAt < u199r && !this.deliveredAt;
});

// ============================================================================
// Static Methods
// ============================================================================

// Update customer stats after order save
// ✅ In Order.js updateCustomerStats static method
gs1u.statics.updateCustomerStats = async function (u7h37n) {
  const fp5za = await this.aggregate([{
    $match: {
      customer: new f530ui.Types.ObjectId(u7h37n),
      orderStatus: {
        $ne: "Cancelled"
      }
    }
  }, {
    $group: {
      _id: null,
      totalOrders: {
        $sum: 1
      },
      totalSpent: {
        $sum: "$totalAmount"
      },
      lastOrderDate: {
        $max: "$createdAt"
      }
    }
  }]);
  const w99i0s = f530ui.model("Customer");

  // ✅ Destructure _id out — never pass it to findByIdAndUpdate
  const {
    _id: otbmf,
    ...wg5f
  } = fp5za[0] || {
    totalOrders: 0,
    totalSpent: 0,
    lastOrderDate: null
  };
  let w2gcl = "New";
  if (wg5f.totalSpent > 10000) w2gcl = "VIP";else if (wg5f.totalOrders > 5) w2gcl = "Regular";else if (wg5f.lastOrderDate && Date.now() - wg5f.lastOrderDate > 90 * 24 * 60 * 60 * 1000) {
    w2gcl = "Inactive";
  }
  await w99i0s.findByIdAndUpdate(u7h37n, {
    ...wg5f,
    segment: w2gcl
  }); // ✅ Clean
};

// ============================================================================
// Post-Save Hook: Update Customer Stats
// ============================================================================
gs1u.post("save", async function (t2l496) {
  try {
    await this.constructor.updateCustomerStats(t2l496.customer);
  } catch (dpwq) {
    console.warn("⚠️ Failed to update customer stats:", dpwq.message);
  }
});

// ============================================================================
// Export Model
// ============================================================================
module.exports = f530ui.model("Order", gs1u);